config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  # get "welcome/say_hello" => "welcome#say"
  # get "welcome" => "welcome#index"
  # root :to => "welcome#index"
  #=================LESSON====================================
  resources :posts do
    resources :comments, except: :show
  end
  resources :categories
  # ================PERSONAL PROJECT====================================

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true

  has_many :post_category_ships
  has_many :posts, through: :post_category_ships

end

app/models/comment.rb
class Comment < ApplicationRecord


  belongs_to :post, counter_cache: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

  default_scope { where(delete_at: nil) }
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :cnum, presence: true

  has_many :comments
  has_many :post_category_ships, dependent: :restrict_with_exception
  has_many :categories, through: :post_category_ships
  belongs_to :user

  def destroy
    update(delete_at: Time.now)
  end
end

app/models/post_category_ship.rb
  class PostCategoryShip < ApplicationRecord
    belongs_to :post
    belongs_to :category
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit ;end

  def update
    if @category.update(params_category)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  before_action :validate_comment_owner, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments.page(params[:page]).per(5)
  end

  def new
    @comment = @post.comments.new
  end


  def create
    @comment = @post.comments.build(params_comment)
    @comment.user = current_user

    @comment = Comment.new(content: params[:comment][:content])
    @comment.post = @post
    @comment.user = current_user


    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end
  def edit ;end

  def update
    if @comment.update(params_comment)
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_comments_path(@post)
  end
  private

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def set_post
    @post = Post.find params[:post_id]
  end

  def params_comment
    params.require(:comment).permit(:content)
  end

  def validate_comment_owner
    unless @comment.user == current_user
      flash[:notice] = 'the comment not belongs to you'
      redirect_to post_comments_path(@post)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :validate_post_owner, only: [:edit, :update, :destroy]


  def index
    @posts = Post.includes(:categories, :user).page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy

    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:fname, :lname, :address, :email, :cnum, :name, category_ids: [])
  end

  def validate_post_owner
    unless @post.user == current_user
      flash[:notice] = 'Unauthorized access to Post:'
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: category_path(@category) } %>

app/views/categories/index.html.erb
<h1>Category</h1>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to :edit, edit_category_path(category) %>
      <%= button_to :delete, category_path(category), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'new', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div id="container">
    <div class="form-wrap">
      <h1>Comment Section</h1>
        <div class="form-group">
          <label for="first-name">Enter Comment Below</label>
          <%= form.text_area :content, class: "input-comment",placeholder: 'Comment' %>
        </div>
          <div class="">
        <div class="submit">  <%= form.submit 'Submit', class: 'btn-submit btn-s2' %></div>
      <% end %>

  </div>
</div>
</div>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.fname %></h1>

<h2>edit comment id: <%= @comment.id %></h2>

<%= render partial: 'form', locals: {post: @post, comment: @comment,  path: post_comment_path(@post, @comment)} %>

app/views/comments/index.html.erb
<h1><%= @post.fname %>'s Recent Comment</h1>




<% @comments.each do |comment| %>

    <table>
      <thead>
      <tr>
        <th colspan="3"><%= comment.content %>(<%= comment.created_at %>)by <%= comment.user.email %></th>
      </tr>
      </thead>
      <tr>
        <td><%= link_to 'edit', edit_post_comment_path(@post, comment), class: "btn-list" %></td>
        <td><%= button_to 'X', post_comment_path(@post, comment), class: "btn-delete", method: :delete %></td>
        <td><%= link_to "Back", posts_path(@post), class: "btn-list" %></td>
      </tr>
    </table>

<% end %>

<div class="btn-standard">
  <%= link_to 'Create New Comment', new_post_comment_path(@post)%>
</div>

<%= paginate @comments %>

app/views/comments/new.html.erb
<h1>Title:
  <% @post.fname %></h1>

<%= render partial: 'form', locals: {post: @post, comment: @comment, path: post_comments_path(@post)} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="../../assets/stylesheets/post_style.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <p></p>
  <nav id="navbar">
    <div class="nav-container">
      <h2 class="nav-logo head-font"><%= "Welcome! #{current_user.email}" if current_user %></h2>
      <ul class="nav-list">
        <li><%= link_to 'View List', posts_path%> </li>
        <li> <%= link_to 'Categories', categories_path %></li>
        <li></li>
        <li></li>
      </ul>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<body>

<% if @post.errors.any? %>
  <ul>
    <% @post.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

<div id="container">
  <div class="form-wrap">
    <h1>Create New Contact Information</h1>
    <%= form_with model: @post do |form| %>
      <div class="form-group">
        <label for="first-name">First Name</label>
        <%= form.text_field :fname, placeholder: 'First Name' %>
        <div class="form-group">
          <label for="last-name">Last Name</label>
          <%= form.text_field :lname, placeholder: 'Last Name' %>
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <%= form.text_field :email, placeholder: 'Email Address' %>
        </div>
        <div class="form-group">
          <label for="address">Address</label>
          <%= form.text_field :address, placeholder: 'Address' %>
        </div>
        <div class="form-group">
          <label for="cnum">Contact Number</label>
          <%= form.text_field :cnum, placeholder: 'Contact Number' %>
        </div>
        <div>
          <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
        </div>
      </div>
      <div class="submit">  <%= form.submit 'Continue', class: 'btn-submit btn-s1' %></div>
    <% end %>
  </div>
</div>
</body>

app/views/posts/edit.html.erb
<h1>Info Name: <%= @post.fname %></h1>
<h2>Post ID: <%= @post.id %></h2>

<%= render partial: 'form', locals: {post: @post, path: posts_path(@post)} %>

app/views/posts/index.html.erb
<body>

    <div class="container">
        <h1>User's Contact Info</h1>
    <div class="table_list">
      <table>
        <thead>
        <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email Address</th>
        <th>Address</th>
        <th>Contact Number</th>
        <th>Comment Counts</th>
        <th>Category</th>
        <th colspan="3">Option</th>
        <th colspan="2">Comment Section</th>
        <th>USER</th>
        </tr>
        </thead>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.fname %></td>
            <td><%= post.lname %></td>
            <td><%= post.email %></td>
            <td><%= post.address %></td>
            <td><%= post.cnum %></td>
            <td><%= post.comments_count %></td>
            <td><%= post.categories.pluck(:name).join(',') %></td>
            <td><%= link_to 'Show', post_path(post), class: 'btn-list' %></td>
            <td><%= link_to 'Edit', edit_post_path(post), class: 'btn-list' if post.user == current_user  %></td>
            <td><%= button_to 'X', post_path(post), method: :delete, class: 'btn-delete'  if post.user == current_user%></td>
            <td><%= link_to 'comments', post_comments_path(post), class: 'btn-list' %></td>
            <td><%= link_to 'new comment', new_post_comment_path(post), class: 'btn-list' %></td>
            <td><%= post.user&.email %></td>
          </tr>
        <% end %>
      </table>
      </div>
    </div>

<div class="btn-standard">

  <%= link_to 'Create new Contact Information', new_post_path %>
</div>

    <%= paginate @posts %>
</body>

app/views/posts/new.html.erb
<%= render partial: 'form', locals: {post: @post, path: posts_path(@post)} %>

app/views/posts/show.html.erb
<h1>Showing Contact Information</h1>
<h2>Contact ID: <%= @post.id %></h2>
<ul>
  <li><%= @post.fname %></li>
  <li><%= @post.lname %></li>
  <li><%= @post.email %></li>
  <li><%= @post.address %></li>
  <li><%= @post.cnum %></li>
</ul>